[package]
name = "llm-driven-runtime"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["tool-macros"]

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 } # 开启 pedantic 规则并设为警告

[lints]
workspace = true

[dependencies]
async-trait = "0.1.92"
serde_json = "1.0.151"
serde = { version = "1.0.229", features = ["derive"] }

[dev-dependencies]
schemars = "1.2.2"
tokio = { version = "1.53.1", features = ["full"] }
tool-macros = { path = "tool-macros" }
